name: Test Data Structures & Algorithms
run-name: ${{ github.actor }} is testing linked lists 🚀
on: [push]
jobs:
  Test-Linked-Lists:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: go test -v ./linkedlists ./adjacencymatrix
