name: Test Data Structures & Algorithms
run-name: ${{ github.actor }} Unit Testing 🚀
on: [push]
jobs:
  Unit-Testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.21.1'
      - run: go test -v ./linkedlists ./adjacencymatrix ./arrays
